name: Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - run: go install github.com/bazelbuild/buildtools/buildifier@latest
      - name: Buildifier format check
        run: buildifier -mode=check civics_test.star
